[rule]
author = ["EZ-E"]
description = """
Threshold set to 1000 TEST\\TEST
"""
from = "now-6m"
name = "IExcessive Web Traffic"
risk_score = 25
severity = "low"
type = "threshold"
rule_id = "11111111-4aeb-44ca-b24b-4a285d7b6ba1"

query = '''
event.dataset : "zeek.http"
'''
[rule.threshold]
field = ["source.ip"]
value = 1000

[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1046"
name = "Network Service Discovery"
reference = "https://attack.mitre.org/techniques/T1046/"

[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"