[rule]
author = ["EZ-E"]
description = """
Detect Nmap or Nikto in user-agent string.
"""
from = "now-6m"
name = "Web Scanning Activity - Nmap and Nikto"
risk_score = 25
severity = "low"
type = "query"
rule_id = "00000000-4aeb-44ca-b24b-4a285d7b6ba1"

query = '''
event.dataset : zeek.http and user_agent.original : *Nikto* or user_agent.original : *Nmap*
'''

[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1046"
name = "Network Service Discovery"
reference = "https://attack.mitre.org/techniques/T1046/"

[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"